### PR TITLE
Fix #86 -- Add support for an optional regex dependency

### LINKED ISSUE #86: support for non-fixed-width pattern look-behind
I noticed that the current default `re` package does not support non-fixed-width pattern look-behind.

And this feature is actually very useful and powerful to have. For example, the following is not supported by `re` but by `regex`.
`(?<=\/\*(\*(?!\/)|[^*])*\*\/(\s|\S)*\n)(?!\/\*(\s|\S)*\n)(.{120,})(?!(\s(?!\/\*)|\S(?!\/\*))*\*\/\n)` 

Is it possible to switch the default `re` to the `regex` package, which supports such a feature? I have issued a PR for it.

### PR DESCRIPTION
**Pull request by yangcht**
Adding a regex example to find line-length issues of any non-comment part of the code.

### CODE REVIEW

**Comment by pinkiepink** [comment]
Sorry. I just realized that `relint` does not support look-behind patterns that are not fixed-width...

**Comment by codingjoe** [comment]
Hi @yangcht,

Thank you for contributing to relint. I always love to see how people use this package.

Would you be so kind and split the cookbook suggestions and the new dependency into two pull-requests? Furthermore, I'd love to keep regex as an optional dependency. So maybe wrap it in a try block and add it to the package extras.

Since we don't actually ship any linting rules, having a separate dependency is not needed in all cases.

Please reach out to me if you require any assistance with that.

Best!
Joe

**Comment by yangcht** [comment]
Hi @codingjoe ,

Thanks for the nice suggestions! I have splitter the PR. I issued another PR for the cookbook change and made this PR only about the usage of the `regex` package.

**Comment by yangcht** [comment]
Hi @codingjoe, I have made the changs for the code plus some tests. Please have a look. Thanks!

**Review by codingjoe — APPROVED** [review]
Hi @yangcht,

Thank you for your contribution. I had this lightly different in mind. Installing dependencies without a user's knowledge is dangerous. Besides, pip doesn't need to be installed on the system, so the command would fail.

Anyhow, I took the liberty to amend a couple of commits and to update the CI suite to test with regex installed.

Please let me know if this works for you, and I will merge and release this patch.

Best,
Joe

**Comment by yangcht** [comment]
Hi @codingjoe,

Thanks for the commits. I agree with your points. I just tested the new version, and it works well.
Please go ahead with the merge and release (the cookbook update is also in another PR).

Cheers,
Chentao

**Pull request merged**
